[package]
name = "differential-evolution"
version = "0.1.0"
authors = ["Martin Ankerl <martin.ankerl@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/martinus/differential-evolution-rs"
homepage = "https://github.com/martinus/differential-evolution-rs"
description = """
Differential evolution optimizer for rust. 
"""
keywords = ["evolution", "optimization", "differential evolution", "DE"]

[dependencies]
clippy = "*"
rand = "0.3"